server:
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: web-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:web-service}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}

fs:
  type: local
  local:
    base-dir: files

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packagesToScan: cn.echcz.webservice.adapter.controller
  api-docs:
    path: /openapi/v3/api-docs
    enabled: false
  swagger-ui:
    path: /openapi/swagger-ui.html

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{transactionId}]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{transactionId}] [%15.15t] %-40.40logger{39} : %m%n%wEx'
  level:
    root: INFO
    org.apache.catalina.startup.DigesterFactory: ERROR
    org.apache.catalina.util.LifecycleBase: ERROR
    org.apache.coyote.http11.Http11NioProtocol: WARN
    org.apache.sshd.common.util.SecurityUtils: WARN
    org.apache.tomcat.util.net.NioSelectorPool: WARN
    org.eclipse.jetty.util.component.AbstractLifeCycle: ERROR
    org.hibernate.validator.internal.util.Version: WARN
    org.springframework.boot.actuate.endpoint.jmx: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
---
spring:
  config:
    activate:
      on-profile: dev,debug
springdoc:
  api-docs:
    enabled: true
test:
  api:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: debug
logging:
  level:
    cn.echcz.webservice: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
