/*
 * This file is generated by jOOQ.
 */
package cn.echcz.webservice.adapter.repository;


import cn.echcz.webservice.adapter.repository.tables.ActionLogTable;
import cn.echcz.webservice.adapter.repository.tables.DocumentTable;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 操作日志
     */
    public static final ActionLogTable ACTION_LOG = ActionLogTable.ACTION_LOG;

    /**
     * 文档
     */
    public static final DocumentTable DOCUMENT = DocumentTable.DOCUMENT;
}
